# Generated by Django 4.2.5 on 2024-01-19 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_crud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=255, null=True)),
                ('lastName', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=255)),
                ('order_date', models.DateTimeField()),
                ('description', models.TextField(null=True)),
                ('pickUp_Location', models.CharField(max_length=255, null=True)),
                ('dropOff_Location', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('incomplete', 'incomplete'), ('rejected', 'rejected')], default='incomplete', max_length=10)),
                ('destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_crud.destination')),
                ('excursions', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_crud.excursions')),
            ],
        ),
    ]
