# Generated by Django 4.2.5 on 2024-01-19 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_crud', '0002_bookings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookings',
        ),
    ]
