# Generated by Django 4.2.5 on 2024-01-22 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_crud', '0006_destinationarea_price_excursions_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinationarea',
            name='longDescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destinationarea',
            name='shotDescription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
