# Generated by Django 4.2.5 on 2024-01-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_crud', '0009_remove_notification_techuser_notification_booking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
