# Generated by Django 4.2.5 on 2024-01-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_crud', '0010_notification_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='excursions',
            old_name='shotDescription',
            new_name='exclusion',
        ),
        migrations.AddField(
            model_name='excursions',
            name='highlight',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='excursions',
            name='inclusion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
